export namespace Keyboard {
  export const Key = {
    ALT: "Alt",
    ALT_GRAPH: "AltGraph",
    ARROW_DOWN: "ArrowDown",
    ARROW_LEFT: "ArrowLeft",
    ARROW_RIGHT: "ArrowRight",
    ARROW_UP: "ArrowUp",
    BACKSPACE: "Backspace",
    CAPS_LOCK: "CapsLock",
    CONTROL: "Control",
    DELETE: "Delete",
    END: "End",
    ENTER: "Enter",
    ESCAPE: "Escape",
    F1: "F1",
    F2: "F2",
    F3: "F3",
    F4: "F4",
    F5: "F5",
    F6: "F6",
    F7: "F7",
    F8: "F8",
    F9: "F9",
    F10: "F10",
    F11: "F11",
    F12: "F12",
    F13: "F13",
    F14: "F14",
    F15: "F15",
    FN_LOCK: "FnLock",
    HOME: "Home",
    HYPER: "Hyper",
    META: "Meta",
    NUM_LOCK: "NumLock",
    PAGE_DOWN: "PageDown",
    PAGE_UP: "PageUp",
    SCROLL_LOCK: "ScrollLock",
    SHIFT: "Shift",
    SPACE: " ",
    SUPER: "Super",
    SYMBOL: "Symbol",
    SYMBOL_LOCK: "SymbolLock",
    TAB: "Tab",
  } as const;
  export type Key = typeof Key[keyof typeof Key];
}
